//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_Multiple_Rename {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advanced_Multiple_Rename.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-PreFix to File Names.
        /// </summary>
        internal static string Add_Preffix_to_Files {
            get {
                return ResourceManager.GetString("Add Preffix to Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Preffix to Folders.
        /// </summary>
        internal static string Add_Preffix_to_Folders {
            get {
                return ResourceManager.GetString("Add Preffix to Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Prefix.
        /// </summary>
        internal static string Add_Prefix {
            get {
                return ResourceManager.GetString("Add Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Suffix.
        /// </summary>
        internal static string Add_Suffix {
            get {
                return ResourceManager.GetString("Add Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Suffix to File Names.
        /// </summary>
        internal static string Add_Suffix_to_Files {
            get {
                return ResourceManager.GetString("Add Suffix to Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Suffix to Folders .
        /// </summary>
        internal static string Add_Suffix_to_Folders {
            get {
                return ResourceManager.GetString("Add Suffix to Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Files  Rename.
        /// </summary>
        internal static string Complete_Files_Rename {
            get {
                return ResourceManager.GetString("Complete Files Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Folders  Rename.
        /// </summary>
        internal static string Complete_Folder_Rename {
            get {
                return ResourceManager.GetString("Complete Folder Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are selected the Complete rename options for files/ folder.
        ///please enter the Name to rename files/folders.
        ///
        ///Note : Entered name will added with incrementing numbers base on based on your selection of asending/ desending.
        ///
        ///Example : entered name = &quot;Sonic&quot;  File/Folder name will be &quot;Sonic-1&quot;, Sonic-2, Sonic-3, etc .
        /// </summary>
        internal static string CompleteRename_message {
            get {
                return ResourceManager.GetString("CompleteRename_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Number of your choice to prefix to file name. 
        ///
        ///Example if you enter 00 , then  first file name added with the prefix &quot;00&quot;-to your existing file Name , second will be &quot;01-filename&quot;. 
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string CustomMessage_2 {
            get {
                return ResourceManager.GetString("CustomMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Number of your choice to add Suffix to file name. 
        ///
        ///Example if you enter 00 , Then first file name added with  Suffix &quot;Existing Filename-00&quot;
        /// second file name will be &quot;Existing Filename-01&quot;. 
        ///
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string CustomMessage_2_Suffix {
            get {
                return ResourceManager.GetString("CustomMessage_2_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name/charchaters of your choice in first text box and Number in second text box.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in first text box &apos;000&apos; in second TextBox ,  the first file name will be prefixed with Shashi-000-filename. and your second file name will be shashi -001-filename.
        ///Note:  filename= your existing file names, and file extenisons which are untouched.
        ///.
        /// </summary>
        internal static string CustomMessage_3 {
            get {
                return ResourceManager.GetString("CustomMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name/charchaters of your choice in first text box and Number in second text box.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in first text box &apos;000&apos; in second TextBox ,  the first file name will be Suffix with &quot; Existing filename- Shashi-000 &quot;
        ///second file name will be  &quot;Existing filename- shashi -001&quot;
        ///
        ///Note:  filename= your existing file names, and file extenisons which are untouched.
        ///.
        /// </summary>
        internal static string CustomMessage_3_Suffix {
            get {
                return ResourceManager.GetString("CustomMessage_3_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choose to enter constant prefix with all your file name , Please Enter Name/charchaters of your choice in the Textbox.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in text box  All of your files are prefixed with Shashi-filename. 
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string CustomMessage_4 {
            get {
                return ResourceManager.GetString("CustomMessage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are  choosen to enter constant suffix with all your file name , Please Enter Name/charchaters of your choice in the Textbox.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in text box  All of your files are Suffix with &quot;Existing filename-Shashi&quot;. 
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string CustomMessage_4_Suffix {
            get {
                return ResourceManager.GetString("CustomMessage_4_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text to Full Rename.
        /// </summary>
        internal static string Enter_Const_Name {
            get {
                return ResourceManager.GetString("Enter_Const_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Constant Prefix Name.
        /// </summary>
        internal static string Enter_Const_Prefix {
            get {
                return ResourceManager.GetString("Enter_Const_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Constant Suffix Name.
        /// </summary>
        internal static string Enter_Const_Suffix {
            get {
                return ResourceManager.GetString("Enter_Const_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Prifix Name.
        /// </summary>
        internal static string Enter_Prefix_Name {
            get {
                return ResourceManager.GetString("Enter_Prefix_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Prifix Number .
        /// </summary>
        internal static string Enter_Prefix_Number {
            get {
                return ResourceManager.GetString("Enter_Prefix_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Suffix Name.
        /// </summary>
        internal static string Enter_Suffix_Name {
            get {
                return ResourceManager.GetString("Enter_Suffix_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Suffix Number.
        /// </summary>
        internal static string Enter_Suffix_Number {
            get {
                return ResourceManager.GetString("Enter_Suffix_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure
        ///Rename of all FIles/Folders are not possible for failure reasons Please checkn the Result column..
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name/charchaters of your choice in first text box and Number in second text box.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in first text box &apos;000&apos; in second TextBox ,  the first Folder name will be Prefix with &quot;Shashi-000-Existing Folder name&quot;
        ///second Folder name will be  &quot;Shashi-001-Existing Folder name&quot;
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched.
        ///.
        /// </summary>
        internal static string FolderPrefix_3 {
            get {
                return ResourceManager.GetString("FolderPrefix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are choosen to enter constant Prefix with all your Folder name , Please Enter Name/charchaters of your choice in the Textbox.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in text box  All of your Folders are Prefix with &quot;Shashi-Existing Folder name &quot;. 
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched..
        /// </summary>
        internal static string FolderPrefix_4 {
            get {
                return ResourceManager.GetString("FolderPrefix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You are selected the Auto number Increment options  to Prefix with Folders name. 
        ///
        ///Example:  First Folder name added with the prefix &quot;00&quot; to your  Existing Folder Name.
        ///Second Folder will &quot;01 Existing Folder Name&quot;. 
        ///Note:  Folder name= your existing Folder names, which are untouched.&quot;.
        /// </summary>
        internal static string FolderPrefix1 {
            get {
                return ResourceManager.GetString("FolderPrefix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Number of your choice to add Prefix to Folder. 
        ///
        ///Example if you enter 00 , Then first Folder is added with  Prefix &quot;00-Existing Folder Name&quot;
        /// second Folder name will be &quot;01-Existing Folder Name&quot;. 
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched..
        /// </summary>
        internal static string FolderPrefix2 {
            get {
                return ResourceManager.GetString("FolderPrefix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name/charchaters of your choice in first text box and Number in second text box.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in first text box &apos;000&apos; in second TextBox ,  the first Folder name will be Suffix with &quot; Existing Folder name-Shashi-000 &quot;
        ///second Folder name will be  &quot;Existing Folder name-shashi -001&quot;
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched.
        ///.
        /// </summary>
        internal static string FolderSuffix_3 {
            get {
                return ResourceManager.GetString("FolderSuffix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are choosen to enter constant suffix with all your Folder name , Please Enter Name/charchaters of your choice in the Textbox.
        ///
        ///Example : If you are entered &apos;Shashi&apos; in text box  All of your Folders are Suffix with &quot;Existing Folder name -Shashi&quot;. 
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched..
        /// </summary>
        internal static string FolderSuffix_4 {
            get {
                return ResourceManager.GetString("FolderSuffix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are selected the Auto number Increment options  to Suffix with Folders name. 
        ///
        ///Example:  First Folder name added with the Suffix &quot;00&quot; to your  Existing Folder Name-00&quot;.
        ///Second Folder will &quot;Existing Folder Name-01&quot;. 
        ///Note:  Folder name= your existing Folder names, which are untouched..
        /// </summary>
        internal static string FolderSuffix1 {
            get {
                return ResourceManager.GetString("FolderSuffix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Number of your choice to add Suffix to Folder. 
        ///
        ///Example if you enter 00 , Then first Folder is added with  Suffix &quot;Existing Folder Name -00&quot;
        /// second Folder name will be &quot;Existing Folder Name-01&quot;. 
        ///
        ///Note:  Folder Name = your existing Folder names, which  are untouched..
        /// </summary>
        internal static string FolderSuffix2 {
            get {
                return ResourceManager.GetString("FolderSuffix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Rename.
        /// </summary>
        internal static string Multiple_rename {
            get {
                return ResourceManager.GetString("Multiple_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Ascending or descending. .
        /// </summary>
        internal static string Please_check_Asc_desc {
            get {
                return ResourceManager.GetString("Please_check_Asc_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        internal static string Please_enter {
            get {
                return ResourceManager.GetString("Please_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Constant Name..
        /// </summary>
        internal static string Please_Enter_Constant_Name {
            get {
                return ResourceManager.GetString("Please_Enter_Constant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Files/Folders you want to rename.
        /// 
        ///By selecting the check box in each row or else Please check Select All check Box in the Grid..
        /// </summary>
        internal static string Please_Sel_GridItems {
            get {
                return ResourceManager.GetString("Please_Sel_GridItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Add-Prefix to Files..
        /// </summary>
        internal static string Please_Sel_Prifx_Type {
            get {
                return ResourceManager.GetString("Please_Sel_Prifx_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Add-Prefix to Folders..
        /// </summary>
        internal static string Please_Sel_Prifx_Type1 {
            get {
                return ResourceManager.GetString("Please_Sel_Prifx_Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Add-Suffix to Files..
        /// </summary>
        internal static string Please_Sel_Suffix_Type {
            get {
                return ResourceManager.GetString("Please_Sel_Suffix_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Add-Suffix to Folders..
        /// </summary>
        internal static string Please_Sel_Suffix_Type1 {
            get {
                return ResourceManager.GetString("Please_Sel_Suffix_Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select File Type..
        /// </summary>
        internal static string Please_Select_FileTpes {
            get {
                return ResourceManager.GetString("Please_Select_FileTpes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Rename Type..
        /// </summary>
        internal static string Please_Select_Rename_Type {
            get {
                return ResourceManager.GetString("Please_Select_Rename_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are selected the Auto number Increment options  to prefix with file name. 
        ///
        ///Example:  First file name added with  the prefix &quot;00&quot;-to your existing file Name , second will be 01-filename. 
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string PrefixMessage {
            get {
                return ResourceManager.GetString("PrefixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming  Process starts Now, Based on your choice 
        ///the selected Items are Rename in #0# order.
        ///
        ///Note: Once this Process starts Dont click on other options in this App, 
        ///if you do, you gone a loose the existing Rename Process..
        /// </summary>
        internal static string Start_Rename {
            get {
                return ResourceManager.GetString("Start_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Process is completed successfull.
        ///More info see Result column in grid..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are selected the Auto number Increment options  to Suffix with file name. 
        ///
        ///Example:  First file name added with the Suffix &quot;00&quot; to your  Existing file Name-00&quot;.
        ///Second file will &quot;Existing file Name-01&quot;. 
        ///Note:  filename= your existing file names, and file extenisons which are untouched..
        /// </summary>
        internal static string SuffixMessage {
            get {
                return ResourceManager.GetString("SuffixMessage", resourceCulture);
            }
        }
    }
}
